In [3]:
import jieba
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import nltk
from nltk.corpus import stopwords

# 載入停用詞
首先，載入NLTK內建的中文停用詞為初始資料

In [4]:
nltk.download('stopwords')
stopWord = set(stopwords.words('chinese'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\styeh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

## 僅為示範綜合效果，繼續疊加中文停用詞表、哈爾濱工業大學停用詞表、百度停用詞表、四川大學機器智能實驗室停用詞表

In [ ]:
with open('./data/hit_stopwords.txt','r',encoding='utf-8') as f:   #載入哈爾濱工業大學停用詞
    for word in f.readlines():
        stopWord.update(word.strip())
with open('./data/cn_stopwords.txt','r',encoding='utf-8') as f:   #載入簡體中文停用詞
    for word in f.readlines():
        stopWord.update(word.strip())
with open('./data/baidu_stopwords.txt','r',encoding='utf-8') as f:   #載入百度停用詞
    for word in f.readlines():
        stopWord.update(word.strip())
with open('./data/scu_stopwords.txt','r',encoding='utf-8') as f:   #載入四川大學機器智能實驗室停用詞
    for word in f.readlines():
        stopWord.update(word.strip())

# 載入電影評論與其標籤，進行斷詞、去除停用詞

In [30]:
import re
def cutword(line):
    review=re.sub(r'[a-zA-Z0-9]*','',line)
    wordList=jieba.lcut(review,cut_all=False)
    return ' '.join([word for word in wordList if word not in stopWord and len(word)>1])
df_zh = pd.read_csv('./data/movie_data_zh.csv', encoding='utf-8')
df_zh['word_list']=df_zh['review'].apply(cutword)
X = df_zh['word_list'].to_numpy()
y = df_zh['sentiment'].to_numpy()
df_zh.head(10)

,review,sentiment,word_list
0,1974年，萬聖節惡作劇之夜，青少年瑪莎·莫克斯利瑪吉·格蕾絲搬到了康涅狄格州格林威治貝勒港...,1,萬聖節 惡作劇 之夜 青少年 瑪莎 克斯 利瑪吉 格蕾絲 康涅狄格州 格林威治 貝勒港 高級...
1,好吧，我真的很喜歡克里斯克里斯托佛森，他在電影時代慣用的輕鬆台詞幫助他實現了輕聲細語的低能量...,0,真的 喜歡 克里斯 克里斯托 佛森 電影 時代慣 能量 風格 他會 費力 一個 場景 消失 ...
2,劇透，如果你想看那部電影，請不要讀這篇文章，雖然這會浪費時間，但情節是如此可預測，無論你讀與...,0,劇透 那部 電影 篇文章 雖然 這會 浪費 時間 情節 預測 無論 區別 郊狼 醜陋 值得 ...
3,嗨，所有看過這部精彩電影的人，我相信你會像我一樣喜歡它，我喜歡這些歌曲，一旦你看過這個節目，...,1,看過 這部 精彩 電影 一樣 喜歡 喜歡 這些 歌曲 看過 這個 節目 唱歌 好像 是節 目...
4,我最近買了DVD，忘記了我是多麼討厭電影版的合唱台詞導演阿滕伯勒對故事所做的每一次改變都失敗...,0,忘記 多麼 討厭電 影版 合唱 台詞 導演 滕伯勒 故事 改變 失敗 因為 導演 卡西 的關...
5,讓 Braik 上演一場精彩的表演 最後，他和 Zorak 在 spac Ghost 之外過...,1,上演 一場 精彩 表演 之外 過著 生活 不得不 喜歡 這兩部 節目 它們 成人 游泳 目的...
6,內森·底特律·弗蘭克·西納特拉是紐約歷史最悠久的浮動擲骰子遊戲的經理，他需要 1000 美元...,1,內森 底特律 弗蘭克 西納 特拉 紐約 歷史 悠久 浮動 骰子 遊戲 經理 美元 來確 保一...
7,要在正確的背景下理解速成課程，您必須了解 80 年代的電視節目，大多數電視節目沒有任何意義，...,1,正確 背景 理解 速成 課程 必須 年代 電視 節目 大多 數電視 節目 沒有 意義 情境 ...
8,一段時間以來，我對查維斯反對全球化的立場印象深刻，但直到我在阿姆斯特丹國際紀錄片電影節上看到...,1,一段 時間 以來 查維斯反 全球化 立場 印象 深刻 阿姆斯特丹 國際紀 錄片 電影節 這部...
9,這部電影由雷尼哈林執導，芬蘭奇蹟史泰龍是加布沃克，貓和老鼠在山上與無情的恐怖分子雷尼哈林知道...,1,這部 電影 雷尼哈林 執導 芬蘭奇 史泰龍 加布 沃克 貓和 老鼠 山上 無情 恐怖分子 雷...

# 給予可能的各參數如下，經過交叉驗證尋找超參數最佳組合
**TfidfVectorizer的選項：vect__超參數名稱**

**LogisticRegression的選項：clf__超參數名稱**

      ngram_range=(1,2) 加入雙詞特徵，
      max_features 限制維度
      max_df=0.8:去除出現在80%文檔中的詞
      min_df=2:只保留至少出現在2個文本中的詞
    總共需要擬合驗證數: (fits)     
      超參數組合數: 2x2x2x2x2x3x2x2 + 1x1x1x2x2x2x2x2x2=384 + 64 = 448
      擬合5個folds: 448x5 = 2240
      超參數組合衝突: 2x2x2x2x2x1x2x1 = 64x5 = 320
      實際擬合驗證數: 2240 - 320 = 1920
X part 已完成斷詞，因此超參數`tokenizer`仍舊維持None。

**須注意運行時間的取捨**

      運行下列程式碼可能超過200分鐘，你可以考慮縮小資料規模(包括訓練樣本或甚至超參數`max_features`)節省時間，但可能得出效果較弱的模型，或者，減少個別超參數的元素來降低超參數的組合數，例如下列`param_grid`先測其中一個，去除不必要的參數元素後，再測另外一個。

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

tfidf = TfidfVectorizer(token_pattern=r'(?u)\b\w\w+\b',
                        max_df=0.8,min_df=2)
# Pipeline of tfidf+logisticregression
tfidf_lreg_pipeline = Pipeline([      
    ('vect', tfidf), 
    ('clf', LogisticRegression(random_state=0))])
param_grid = [{'vect__ngram_range': [(1,1),(1,2)],
               'vect__norm':['l1','l2'],
               'vect__max_features':[1000,1500],
               'vect__max_df':[0.8,0.9],
               'vect__min_df':[2,4],
               'clf__l1_ratio': [0,1,0.5],
               'clf__C': [1.0, 10.0],
               'clf__solver': ['liblinear','saga']},
              {'vect__ngram_range': [(1,1)],
               'vect__use_idf':[False],
               'vect__norm':[None],
               'vect__max_features':[1000,1500],
               'vect__max_df':[0.7,0.8],
               'vect__min_df':[2,6],
               'clf__l1_ratio': [0,1],
               'clf__C': [1.0, 10.0],
               'clf__solver': ['liblinear','lbfgs']},
              ]
gs_lr_tfidf = GridSearchCV(tfidf_lreg_pipeline, param_grid,     # 評估
                           scoring='accuracy',
                           cv=5,
                           verbose=2,
                           n_jobs=-1)
gs_lr_tfidf.fit(X, y)

上面程式分成5疊(5 fold)樣本進行交叉驗證正確率(accuracy)，其最後得出最佳準確度(`best_score_`)係為此5次的平均。

In [35]:
print('最佳超參數集: %s ' % gs_lr_tfidf.best_params_)
print('交叉驗證最佳準確度: %.3f' % gs_lr_tfidf.best_score_)

最佳超參數集: {'clf__C': 1.0, 'clf__l1_ratio': 0.5, 'clf__solver': 'saga', 'vect__max_df': 0.8, 'vect__max_features': 1500, 'vect__min_df': 2, 'vect__ngram_range': (1, 1), 'vect__norm': 'l2'}
交叉驗證最佳準確度: 0.859

# 擬合、轉換
#### 使用如上交叉驗證得出的最佳超參數組：{'clf__C': 1.0, 'clf__l1_ratio': 0.5, 'clf__solver': 'saga', 'vect__max_df': 0.8, 'vect__max_features': 1500, 'vect__min_df': 2, 'vect__ngram_range': (1, 1), 'vect__norm': 'l2'}

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.01, random_state=42)
vectorizer = TfidfVectorizer(ngram_range=(1,1), max_features=1500,
                             norm='l2',
                             max_df=0.8,min_df=2)
X_train_tfidf = vectorizer.fit_transform(X_train)
model = LogisticRegression(C=1.0, l1_ratio=0.5,solver='saga')  # C 為正則化強度
model.fit(X_train_tfidf, y_train)

LogisticRegression(l1_ratio=0.5, solver='saga')

In [64]:
print("數字向量詞彙集:",vectorizer.vocabulary_.items())
y_pred_train = model.predict(X_train_tfidf)
print("訓練集準確率:",accuracy_score(y_train, y_pred_train))
X_test_tfidf = vectorizer.transform(X_test)
y_pred_test = model.predict(X_test_tfidf)
print("測試集準確率:",accuracy_score(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))
y_pred_proba=model.predict_proba(X_test_tfidf)
df_1 = pd.DataFrame({'真實標籤':y_test,'預測標籤':y_pred_test,'類別0機率':y_pred_proba[:,0],'類別1機率':y_pred_proba[:,1]})
df_1[(df_1['預測標籤']!=df_1['真實標籤'])]

數字向量詞彙集: dict_items([('史蒂夫', np.int64(302)), ('一位', np.int64(3)), ('紐約', np.int64(1095)), ('公寓', np.int64(207)), ('母親', np.int64(859)), ('一個', np.int64(4)), ('漂亮', np.int64(911)), ('名叫', np.int64(316)), ('結婚', np.int64(1101)), ('沒有', np.int64(879)), ('主角', np.int64(91)), ('那裡', np.int64(1392)), ('提供', np.int64(715)), ('已經', np.int64(504)), ('成功', np.int64(643)), ('冒險', np.int64(215)), ('東西', np.int64(819)), ('支持', np.int64(733)), ('這部', np.int64(1355)), ('電影會', np.int64(1439)), ('道德', np.int64(1371)), ('演出', np.int64(913)), ('這位', np.int64(1333)), ('觀眾', np.int64(1230)), ('看來', np.int64(1030)), ('這是', np.int64(1344)), ('一部', np.int64(32)), ('糟糕', np.int64(1090)), ('劇本', np.int64(240)), ('情節', np.int64(606)), ('台詞', np.int64(300)), ('雖然', np.int64(1432)), ('討人', np.int64(1237)), ('喜歡', np.int64(338)), ('很多', np.int64(560)), ('令人', np.int64(123)), ('討厭', np.int64(1238)), ('材料', np.int64(818)), ('角色', np.int64(1233)), ('時間', np.int64(781)), ('畢竟', np.int64(993)), ('起來', np.int64(1289)), ('很漂亮', np.int64(566)), ('講述', np.int64(1273)), ('團隊', np.int64(361)), ('透過', np.int64(1325)), ('進行', np.int64(1363)), ('探索', np.int64(704)), ('一邊', np.int64(31)), ('等待', np.int64(1074)), ('驚喜', np.int64(1478)), ('上映', np.int64(44)), ('看過', np.int64(1034)), ('這個', np.int64(1334)), ('系列', np.int64(1091)), ('一集', np.int64(35)), ('到底', np.int64(227)), ('像是', np.int64(180)), ('很棒', np.int64(565)), ('印象', np.int64(267)), ('事實', np.int64(101)), ('簡單', np.int64(1079)), ('科幻', np.int64(1055)), ('有史', np.int64(798)), ('有趣', np.int64(801)), ('興奮', np.int64(1173)), ('小說', np.int64(488)), ('什麼', np.int64(116)), ('因為', np.int64(351)), ('驚嘆', np.int64(1479)), ('前提', np.int64(231)), ('價值', np.int64(181)), ('超過', np.int64(1294)), ('認為', np.int64(1262)), ('例子', np.int64(145)), ('一種', np.int64(26)), ('媒體', np.int64(443)), ('能夠', np.int64(1160)), ('觀看', np.int64(1229)), ('他們', np.int64(118)), ('情況', np.int64(605)), ('隨著', np.int64(1430)), ('熟悉', np.int64(939)), ('並且', np.int64(75)), ('增加', np.int64(386)), ('能力', np.int64(1159)), ('難以', np.int64(1435)), ('置信', np.int64(1133)), ('一切都是', np.int64(7)), ('出色', np.int64(222)), ('寫作', np.int64(474)), ('工作', np.int64(501)), ('人員', np.int64(110)), ('目的', np.int64(1023)), ('結果', np.int64(1105)), ('過去', np.int64(1367)), ('不斷', np.int64(65)), ('偉大', np.int64(163)), ('害怕', np.int64(463)), ('改變', np.int64(735)), ('挑戰', np.int64(699)), ('關注', np.int64(1423)), ('總是', np.int64(1122)), ('劇集', np.int64(243)), ('相當', np.int64(1026)), ('相關', np.int64(1027)), ('威脅', np.int64(439)), ('越來', np.int64(1295)), ('專注', np.int64(479)), ('地球', np.int64(367)), ('攻擊', np.int64(736)), ('幾乎', np.int64(528)), ('藉口', np.int64(1194)), ('雜的', np.int64(1433)), ('包括', np.int64(257)), ('問題', np.int64(335)), ('時刻', np.int64(777)), ('旅行', np.int64(765)), ('敵人', np.int64(752)), ('傑克', np.int64(171)), ('人類', np.int64(115)), ('戰鬥', np.int64(664)), ('一場', np.int64(12)), ('基本上', np.int64(378)), ('這在', np.int64(1337)), ('恥辱', np.int64(597)), ('每個', np.int64(860)), ('星球', np.int64(772)), ('呈現', np.int64(322)), ('潛力', np.int64(918)), ('衝突', np.int64(1205)), ('精彩', np.int64(1084)), ('本質', np.int64(815)), ('結局', np.int64(1103)), ('感覺', np.int64(633)), ('繼續', np.int64(1126)), ('參與', np.int64(281)), ('專業', np.int64(478)), ('敘述', np.int64(746)), ('內容', np.int64(196)), ('回到', np.int64(348)), ('開始', np.int64(1417)), ('歡迎', np.int64(848)), ('最終', np.int64(796)), ('事情', np.int64(102)), ('還是', np.int64(1384)), ('這樣', np.int64(1347)), ('很難', np.int64(569)), ('發現', np.int64(1013)), ('結束', np.int64(1104)), ('無論', np.int64(930)), ('時間裡', np.int64(782)), ('美麗', np.int64(1139)), ('風景', np.int64(1472)), ('出演', np.int64(219)), ('真實', np.int64(1035)), ('證明', np.int64(1275)), ('我們', np.int64(653)), ('記住', np.int64(1241)), ('作為', np.int64(140)), ('放映', np.int64(738)), ('幾次', np.int64(531)), ('每次', np.int64(861)), ('電影時', np.int64(1438)), ('之外', np.int64(93)), ('任何人', np.int64(128)), ('一段', np.int64(23)), ('才能', np.int64(674)), ('進入', np.int64(1361)), ('整個', np.int64(749)), ('房間', np.int64(669)), ('尖叫', np.int64(492)), ('體驗', np.int64(1482)), ('表演', np.int64(1208)), ('垃圾', np.int64(371)), ('擁有', np.int64(728)), ('朋友', np.int64(805)), ('相比', np.int64(1025)), ('唯一一', np.int64(332)), ('這種', np.int64(1350)), ('一開始', np.int64(34)), ('喜劇', np.int64(337)), ('變成', np.int64(1281)), ('約翰', np.int64(1093)), ('成為', np.int64(647)), ('明星', np.int64(768)), ('當然', np.int64(1004)), ('忽視', np.int64(586)), ('四個', np.int64(346)), ('女兒', np.int64(420)), ('感情', np.int64(631)), ('迷人', np.int64(1316)), ('愛上', np.int64(623)), ('大部分', np.int64(402)), ('邁克爾', np.int64(1382)), ('兄弟', np.int64(186)), ('堅持', np.int64(382)), ('場景', np.int64(383)), ('拍攝', np.int64(693)), ('影片', np.int64(555)), ('亮點', np.int64(107)), ('足以', np.int64(1296)), ('肥皂', np.int64(1155)), ('傑作', np.int64(170)), ('演員陣容', np.int64(916)), ('公平', np.int64(208)), ('殘酷', np.int64(855)), ('刺激', np.int64(228)), ('純粹', np.int64(1096)), ('令人不安', np.int64(124)), ('劇透', np.int64(241)), ('怪物', np.int64(592)), ('伯特', np.int64(133)), ('白痴', np.int64(1017)), ('一樣', np.int64(21)), ('試圖', np.int64(1259)), ('警察', np.int64(1277)), ('覺得', np.int64(1228)), ('演員', np.int64(914)), ('恐怖', np.int64(594)), ('那樣', np.int64(1390)), ('第二', np.int64(1071)), ('靈感', np.int64(1446)), ('人來', np.int64(108)), ('你會', np.int64(143)), ('確實', np.int64(1045)), ('混合', np.int64(898)), ('不僅僅', np.int64(48)), ('人們', np.int64(109)), ('中心', np.int64(81)), ('包含', np.int64(256)), ('英雄', np.int64(1184)), ('處理', np.int64(1198)), ('當我', np.int64(1001)), ('我並', np.int64(650)), ('希望', np.int64(512)), ('這裡', np.int64(1353)), ('經歷', np.int64(1113)), ('不幸', np.int64(58)), ('嚴肅', np.int64(344)), ('這一點', np.int64(1328)), ('殺手', np.int64(857)), ('它們', np.int64(453)), ('很少', np.int64(562)), ('死亡', np.int64(853)), ('一點', np.int64(39)), ('搞笑', np.int64(723)), ('有人', np.int64(797)), ('驚訝', np.int64(1481)), ('理查德', np.int64(971)), ('斯特', np.int64(757)), ('執導', np.int64(376)), ('再也', np.int64(212)), ('機會', np.int64(840)), ('失望', np.int64(414)), ('時候', np.int64(775)), ('電視', np.int64(1442)), ('再次', np.int64(213)), ('屏幕', np.int64(497)), ('想像', np.int64(610)), ('一群', np.int64(28)), ('模仿', np.int64(836)), ('它會', np.int64(454)), ('可怕', np.int64(295)), ('平淡', np.int64(518)), ('成熟', np.int64(648)), ('失敗', np.int64(413)), ('讀過', np.int64(1278)), ('這本書', np.int64(1346)), ('只能', np.int64(293)), ('伯格', np.int64(132)), ('剛剛', np.int64(232)), ('可悲', np.int64(296)), ('評論', np.int64(1256)), ('高興', np.int64(1486)), ('天才', np.int64(405)), ('許是', np.int64(1252)), ('最偉大', np.int64(793)), ('那部', np.int64(1393)), ('作品', np.int64(138)), ('欣賞', np.int64(843)), ('摩爾', np.int64(725)), ('詹姆斯', np.int64(1260)), ('描述', np.int64(714)), ('芭芭拉', np.int64(1181)), ('吸引', np.int64(319)), ('幸福', np.int64(523)), ('金發', np.int64(1408)), ('驚人', np.int64(1477)), ('想要', np.int64(614)), ('追求', np.int64(1320)), ('性感', np.int64(590)), ('優秀', np.int64(182)), ('自我', np.int64(1164)), ('原始', np.int64(272)), ('扭曲', np.int64(679)), ('眼睛', np.int64(1038)), ('傳達', np.int64(176)), ('大多', np.int64(394)), ('政府', np.int64(740)), ('記得', np.int64(1242)), ('這些', np.int64(1331)), ('幾年', np.int64(530)), ('找到', np.int64(682)), ('標題', np.int64(835)), ('感到', np.int64(628)), ('有點', np.int64(804)), ('不用', np.int64(67)), ('無聊', np.int64(927)), ('煩人', np.int64(938)), ('總體', np.int64(1125)), ('電影並', np.int64(1436)), ('值得一看', np.int64(160)), ('觀點', np.int64(1231)), ('當地', np.int64(999)), ('商店', np.int64(334)), ('美元', np.int64(1134)), ('我覺', np.int64(662)), ('不錯', np.int64(70)), ('適合', np.int64(1374)), ('這對', np.int64(1341)), ('是關', np.int64(773)), ('值得', np.int64(159)), ('封面', np.int64(476)), ('還不錯', np.int64(1383)), ('世界', np.int64(71)), ('故事', np.int64(742)), ('多麼', np.int64(393)), ('尋找', np.int64(481)), ('充滿', np.int64(187)), ('恐怖片', np.int64(595)), ('那麼', np.int64(1394)), ('檢查', np.int64(841)), ('加拿大', np.int64(247)), ('導演', np.int64(484)), ('智慧', np.int64(785)), ('藝術', np.int64(1195)), ('影院', np.int64(557)), ('我個', np.int64(652)), ('年代', np.int64(520)), ('描繪', np.int64(712)), ('被困', np.int64(1212)), ('鏡頭', np.int64(1414)), ('想法', np.int64(613)), ('方向', np.int64(761)), ('行動', np.int64(1203)), ('項目', np.int64(1455)), ('地位', np.int64(363)), ('邏輯', np.int64(1388)), ('一系列', np.int64(27)), ('事件', np.int64(100)), ('陷入', np.int64(1428)), ('無法', np.int64(926)), ('控制', np.int64(709)), ('不想', np.int64(62)), ('透露', np.int64(1326)), ('樂趣', np.int64(831)), ('當今', np.int64(995)), ('時代', np.int64(774)), ('頭腦', np.int64(1463)), ('公司', np.int64(204)), ('美國', np.int64(1135)), ('地方', np.int64(365)), ('困惑', np.int64(354)), ('這並', np.int64(1329)), ('奇怪', np.int64(415)), ('婚姻', np.int64(441)), ('告訴', np.int64(323)), ('生活', np.int64(981)), ('並不像', np.int64(74)), ('表面', np.int64(1211)), ('不會', np.int64(66)), ('其餘', np.int64(210)), ('影響', np.int64(558)), ('曲折', np.int64(788)), ('展示', np.int64(498)), ('看似', np.int64(1029)), ('天賦', np.int64(407)), ('當他', np.int64(996)), ('陰謀', np.int64(1427)), ('驚悚片', np.int64(1480)), ('意識', np.int64(621)), ('身份', np.int64(1305)), ('一部分', np.int64(33)), ('主題', np.int64(92)), ('震驚', np.int64(1445)), ('背景', np.int64(1157)), ('預算', np.int64(1460)), ('旅程', np.int64(764)), ('角度', np.int64(1232)), ('富有', np.int64(466)), ('同情心', np.int64(312)), ('人物', np.int64(114)), ('男人', np.int64(986)), ('他會', np.int64(119)), ('大衛', np.int64(401)), ('表現', np.int64(1209)), ('秘密', np.int64(1056)), ('看起', np.int64(1033)), ('精心', np.int64(1085)), ('懸念', np.int64(640)), ('心理', np.int64(577)), ('遊戲', np.int64(1364)), ('經常', np.int64(1112)), ('賦予', np.int64(1285)), ('出現', np.int64(220)), ('通過', np.int64(1359)), ('力量', np.int64(244)), ('滿意', np.int64(909)), ('方式', np.int64(762)), ('一幕', np.int64(15)), ('完美', np.int64(459)), ('現在', np.int64(968)), ('忠實', np.int64(582)), ('粉絲', np.int64(1082)), ('帶著', np.int64(515)), ('年齡', np.int64(522)), ('孩子', np.int64(448)), ('暴力', np.int64(787)), ('超出', np.int64(1290)), ('兒童', np.int64(194)), ('期待', np.int64(807)), ('推薦', np.int64(710)), ('這件', np.int64(1332)), ('整部', np.int64(750)), ('狀態', np.int64(960)), ('時尚', np.int64(778)), ('指導', np.int64(698)), ('從頭', np.int64(571)), ('娛樂', np.int64(440)), ('微笑', np.int64(573)), ('不再', np.int64(50)), ('對話', np.int64(483)), ('高潮', np.int64(1485)), ('分鐘', np.int64(225)), ('音樂', np.int64(1452)), ('序列', np.int64(533)), ('魔法', np.int64(1491)), ('顯然', np.int64(1470)), ('內心', np.int64(197)), ('靈魂', np.int64(1447)), ('必看', np.int64(578)), ('其他人', np.int64(209)), ('更好', np.int64(789)), ('本身', np.int64(816)), ('明確', np.int64(770)), ('女性', np.int64(425)), ('某種', np.int64(822)), ('神秘', np.int64(1049)), ('超越', np.int64(1293)), ('城市', np.int64(375)), ('關心', np.int64(1421)), ('進展', np.int64(1362)), ('接近', np.int64(708)), ('視覺', np.int64(1226)), ('深刻', np.int64(895)), ('發展', np.int64(1010)), ('唯一', np.int64(331)), ('原因', np.int64(271)), ('吉米', np.int64(308)), ('現場', np.int64(969)), ('痛苦', np.int64(1005)), ('當他們', np.int64(997)), ('播放', np.int64(727)), ('比賽', np.int64(866)), ('片段', np.int64(949)), ('不得不', np.int64(59)), ('發出', np.int64(1009)), ('聲音', np.int64(1150)), ('不必', np.int64(60)), ('聽到', np.int64(1152)), ('忍受', np.int64(580)), ('扮演', np.int64(680)), ('應該', np.int64(638)), ('緊張', np.int64(1117)), ('古怪', np.int64(290)), ('獲得', np.int64(965)), ('奧斯卡獎', np.int64(417)), ('浪漫', np.int64(891)), ('實際上', np.int64(472)), ('男性', np.int64(989)), ('合作', np.int64(305)), ('化學', np.int64(258)), ('反應', np.int64(283)), ('朱莉', np.int64(817)), ('愚蠢', np.int64(622)), ('積極', np.int64(1060)), ('職業', np.int64(1151)), ('生涯', np.int64(982)), ('很大', np.int64(561)), ('幫助', np.int64(516)), ('停止', np.int64(167)), ('湯姆', np.int64(903)), ('克斯', np.int64(189)), ('澳大利', np.int64(919)), ('銀幕', np.int64(1410)), ('離開', np.int64(1434)), ('一名', np.int64(10)), ('發生', np.int64(1014)), ('調查', np.int64(1269)), ('並在', np.int64(76)), ('沉悶', np.int64(877)), ('片中', np.int64(947)), ('動作', np.int64(251)), ('那種', np.int64(1391)), ('廣播', np.int64(537)), ('樣子', np.int64(838)), ('解決', np.int64(1234)), ('殺案', np.int64(858)), ('年前', np.int64(521)), ('青少年', np.int64(1448)), ('詞濫調', np.int64(1258)), ('女孩', np.int64(423)), ('幸運', np.int64(524)), ('飾演', np.int64(1475)), ('牛仔', np.int64(951)), ('遺忘', np.int64(1380)), ('蹩腳', np.int64(1303)), ('關於', np.int64(1422)), ('黑人', np.int64(1495)), ('動作片', np.int64(252)), ('比利', np.int64(864)), ('厭倦', np.int64(276)), ('種族', np.int64(1059)), ('主義的', np.int64(89)), ('輕人', np.int64(1309)), ('決定', np.int64(875)), ('手中', np.int64(673)), ('現實', np.int64(970)), ('利用', np.int64(226)), ('白人', np.int64(1016)), ('虐待', np.int64(1197)), ('傷害', np.int64(177)), ('社會', np.int64(1047)), ('黑幫', np.int64(1496)), ('女士', np.int64(421)), ('並將', np.int64(77)), ('可憐', np.int64(298)), ('監獄', np.int64(1021)), ('必須', np.int64(579)), ('特工', np.int64(955)), ('實驗', np.int64(473)), ('各種', np.int64(304)), ('超級', np.int64(1291)), ('拯救', np.int64(695)), ('華橫溢', np.int64(1187)), ('迄今', np.int64(1312)), ('為止', np.int64(924)), ('缺乏', np.int64(1128)), ('優點', np.int64(183)), ('幽默', np.int64(526)), ('有時', np.int64(800)), ('電影來', np.int64(1437)), ('很長', np.int64(568)), ('期望', np.int64(808)), ('麥克', np.int64(1493)), ('克里斯', np.int64(191)), ('这部', np.int64(1313)), ('电影', np.int64(985)), ('至少', np.int64(1169)), ('家庭', np.int64(465)), ('男孩', np.int64(988)), ('黑暗', np.int64(1497)), ('氣氛', np.int64(872)), ('愉快', np.int64(616)), ('顯示', np.int64(1471)), ('有限', np.int64(803)), ('留下', np.int64(991)), ('空間', np.int64(1061)), ('比爾', np.int64(865)), ('微妙', np.int64(572)), ('從來', np.int64(570)), ('類型', np.int64(1468)), ('做作', np.int64(165)), ('水平', np.int64(873)), ('情緒', np.int64(607)), ('信息', np.int64(155)), ('整體', np.int64(751)), ('南方', np.int64(262)), ('不喜歡', np.int64(53)), ('無關', np.int64(932)), ('之間', np.int64(96)), ('機器', np.int64(839)), ('投票', np.int64(688)), ('公室', np.int64(206)), ('代表', np.int64(122)), ('多年', np.int64(392)), ('嘲笑', np.int64(341)), ('美國人', np.int64(1136)), ('剩下', np.int64(234)), ('誠實', np.int64(1266)), ('總統', np.int64(1124)), ('真相', np.int64(1037)), ('這張', np.int64(1342)), ('洛克', np.int64(887)), ('裡面', np.int64(1215)), ('女王', np.int64(427)), ('大約', np.int64(399)), ('一分', np.int64(6)), ('廢話', np.int64(535)), ('很酷', np.int64(567)), ('生氣', np.int64(980)), ('錯誤', np.int64(1412)), ('原著', np.int64(274)), ('這兩部', np.int64(1336)), ('想起', np.int64(615)), ('克里斯托弗', np.int64(192)), ('兩部', np.int64(202)), ('毛骨悚然', np.int64(867)), ('無能', np.int64(929)), ('留在', np.int64(992)), ('期間', np.int64(809)), ('可笑', np.int64(299)), ('特別', np.int64(953)), ('女人', np.int64(419)), ('穿著', np.int64(1062)), ('憤怒', np.int64(637)), ('概念', np.int64(830)), ('混蛋', np.int64(899)), ('我會', np.int64(656)), ('厭惡', np.int64(277)), ('兩次', np.int64(201)), ('國王', np.int64(358)), ('我無法', np.int64(658)), ('家人', np.int64(464)), ('做出', np.int64(166)), ('行為', np.int64(1204)), ('真的', np.int64(1036)), ('父親', np.int64(945)), ('活力', np.int64(888)), ('快樂', np.int64(583)), ('基督教', np.int64(379)), ('弄清楚', np.int64(541)), ('信仰', np.int64(154)), ('目標', np.int64(1022)), ('迷失', np.int64(1318)), ('導致', np.int64(485)), ('印度', np.int64(266)), ('殺戮', np.int64(856)), ('變化', np.int64(1279)), ('建議', np.int64(540)), ('方法', np.int64(763)), ('聖誕節', np.int64(1148)), ('沮喪', np.int64(881)), ('看法', np.int64(1031)), ('還有', np.int64(1385)), ('好萊塢', np.int64(432)), ('編劇', np.int64(1119)), ('認真', np.int64(1263)), ('投入', np.int64(687)), ('比亞', np.int64(863)), ('原創', np.int64(270)), ('將其', np.int64(477)), ('拒絕', np.int64(694)), ('兩個', np.int64(200)), ('那個', np.int64(1389)), ('瘋狂', np.int64(1008)), ('裸體', np.int64(1216)), ('產生', np.int64(984)), ('付出', np.int64(120)), ('努力', np.int64(249)), ('醫生', np.int64(1404)), ('死去', np.int64(854)), ('姐妹', np.int64(437)), ('自殺', np.int64(1165)), ('傾向', np.int64(179)), ('但當', np.int64(134)), ('悲劇', np.int64(601)), ('足夠', np.int64(1297)), ('博士', np.int64(263)), ('身體', np.int64(1307)), ('肯定', np.int64(1156)), ('愛好者', np.int64(624)), ('早期', np.int64(767)), ('同性', np.int64(310)), ('酒吧', np.int64(1401)), ('遵循', np.int64(1377)), ('逃離', np.int64(1324)), ('經典', np.int64(1111)), ('數字', np.int64(754)), ('編輯', np.int64(1120)), ('效果', np.int64(744)), ('醫院', np.int64(1405)), ('拉斯', np.int64(692)), ('追捕', np.int64(1319)), ('怎麼', np.int64(587)), ('飛機', np.int64(1474)), ('回答', np.int64(350)), ('人性', np.int64(111)), ('身上', np.int64(1304)), ('客串', np.int64(461)), ('悲傷', np.int64(600)), ('歷史', np.int64(852)), ('見過', np.int64(1223)), ('尷尬', np.int64(493)), ('演員們', np.int64(915)), ('噩夢', np.int64(342)), ('轉變', np.int64(1311)), ('警告', np.int64(1276)), ('特技', np.int64(956)), ('引人注目', np.int64(543)), ('曾經', np.int64(791)), ('答案', np.int64(1075)), ('這兩個', np.int64(1335)), ('忘記', np.int64(581)), ('日本', np.int64(766)), ('吸血鬼', np.int64(321)), ('國家', np.int64(357)), ('強烈', np.int64(549)), ('情感', np.int64(604)), ('太棒了', np.int64(409)), ('這麼', np.int64(1358)), ('語言', np.int64(1265)), ('創作', np.int64(237)), ('歌手', np.int64(845)), ('主演', np.int64(87)), ('根據', np.int64(826)), ('捕捉到', np.int64(701)), ('確定', np.int64(1044)), ('主意', np.int64(86)), ('感受', np.int64(630)), ('周圍', np.int64(324)), ('甜蜜', np.int64(977)), ('模糊', np.int64(837)), ('以來', np.int64(127)), ('不僅', np.int64(47)), ('遺憾', np.int64(1381)), ('選擇', np.int64(1378)), ('犯罪', np.int64(959)), ('並不', np.int64(73)), ('感興趣', np.int64(632)), ('吸引力', np.int64(320)), ('預測', np.int64(1459)), ('說過', np.int64(1268)), ('當它', np.int64(1000)), ('一份', np.int64(2)), ('加里', np.int64(248)), ('網絡', np.int64(1116)), ('肖恩', np.int64(1154)), ('還沒有', np.int64(1386)), ('變得', np.int64(1280)), ('很快', np.int64(563)), ('播出', np.int64(726)), ('節目', np.int64(1077)), ('跳過', np.int64(1302)), ('老實', np.int64(1143)), ('標準', np.int64(833)), ('加上', np.int64(246)), ('意義', np.int64(620)), ('實話', np.int64(470)), ('浪費', np.int64(892)), ('粗俗', np.int64(1083)), ('動機', np.int64(253)), ('文化', np.int64(755)), ('特定', np.int64(954)), ('絕對', np.int64(1108)), ('我給', np.int64(660)), ('戲劇', np.int64(665)), ('開心', np.int64(1418)), ('典型', np.int64(211)), ('第二次', np.int64(1072)), ('第一次', np.int64(1068)), ('不好', np.int64(56)), ('小電影', np.int64(490)), ('巴里', np.int64(505)), ('一如既往', np.int64(13)), ('廣告', np.int64(536)), ('大腦', np.int64(400)), ('實際', np.int64(471)), ('高中', np.int64(1483)), ('學生', np.int64(450)), ('小時', np.int64(487)), ('美好', np.int64(1137)), ('這絕', np.int64(1351)), ('考慮', np.int64(1147)), ('因素', np.int64(352)), ('看著', np.int64(1032)), ('名字', np.int64(317)), ('破壞', np.int64(1042)), ('太多', np.int64(408)), ('毫無疑問', np.int64(870)), ('好電影', np.int64(433)), ('持續', np.int64(696)), ('傳奇', np.int64(174)), ('有關', np.int64(802)), ('領域', np.int64(1462)), ('主義', np.int64(88)), ('同情', np.int64(311)), ('享受', np.int64(106)), ('襲擊', np.int64(1217)), ('現代', np.int64(967)), ('血腥', np.int64(1202)), ('技巧', np.int64(684)), ('嘗試', np.int64(340)), ('結構', np.int64(1106)), ('至於', np.int64(1170)), ('一堆', np.int64(11)), ('所知', np.int64(671)), ('傳統', np.int64(175)), ('當時', np.int64(1003)), ('一本', np.int64(19)), ('副本', np.int64(236)), ('準備', np.int64(904)), ('西部片', np.int64(1222)), ('服裝', np.int64(806)), ('保留', np.int64(150)), ('精神', np.int64(1086)), ('鄉村', np.int64(1397)), ('藝術家', np.int64(1196)), ('歌曲', np.int64(846)), ('西部', np.int64(1221)), ('成長', np.int64(649)), ('承認', np.int64(683)), ('負責', np.int64(1283)), ('上帝', np.int64(43)), ('核心', np.int64(825)), ('衣服', np.int64(1206)), ('滿分', np.int64(908)), ('錄片', np.int64(1411)), ('外星人', np.int64(389)), ('太空', np.int64(410)), ('紀錄片', np.int64(1092)), ('尼克', np.int64(494)), ('政治', np.int64(741)), ('成員', np.int64(644)), ('布魯斯', np.int64(510)), ('關鍵', np.int64(1424)), ('視頻', np.int64(1227)), ('上觀', np.int64(45)), ('丹尼', np.int64(84)), ('某人', np.int64(820)), ('攝影', np.int64(731)), ('般的', np.int64(1177)), ('評分', np.int64(1254)), ('購買', np.int64(1287)), ('路易斯', np.int64(1300)), ('著名', np.int64(1190)), ('墨西哥', np.int64(387)), ('宗教', np.int64(460)), ('非凡', np.int64(1449)), ('牧師', np.int64(952)), ('一个', np.int64(0)), ('妓女', np.int64(434)), ('西班牙', np.int64(1220)), ('塑造', np.int64(385)), ('最佳', np.int64(792)), ('簡直', np.int64(1080)), ('舞台', np.int64(1175)), ('侮辱', np.int64(146)), ('希特勒', np.int64(513)), ('頂級', np.int64(1454)), ('英國', np.int64(1182)), ('不應', np.int64(63)), ('一件', np.int64(1)), ('外觀', np.int64(391))

     真實標籤  預測標籤     類別0機率     類別1機率
1       0     1  0.416703  0.583297
4       0     1  0.403269  0.596731
20      1     0  0.827140  0.172860
24      0     1  0.110171  0.889829
32      0     1  0.454087  0.545913
36      1     0  0.547536  0.452464
37      1     0  0.781841  0.218159
38      0     1  0.282799  0.717201
40      1     0  0.566315  0.433685
47      0     1  0.338434  0.661566
49      1     0  0.828840  0.171160
51      0     1  0.466859  0.533141
58      0     1  0.483513  0.516487
60      0     1  0.492615  0.507385
90      0     1  0.144825  0.855175
91      1     0  0.545239  0.454761
92      1     0  0.809707  0.190293
114     1     0  0.747133  0.252867
141     0     1  0.459855  0.540145
160     0     1  0.227959  0.772041
176     0     1  0.123498  0.876502
179     1     0  0.706403  0.293597
181     0     1  0.492735  0.507265
194     1     0  0.642709  0.357291
204     0     1  0.452148  0.547852
214     0     1  0.283139  0.716861
225     0     1  0.204240  0.795760
234     0     1  0.410205  0.589795
239     1     0  0.653962  0.346038
243     1     0  0.698951  0.301049
252     0     1  0.241321  0.758679
268     0     1  0.474254  0.525746
271     0     1  0.492735  0.507265
272     1     0  0.545683  0.454317
282     0     1  0.495333  0.504667
286     0     1  0.395360  0.604640
287     1     0  0.603515  0.396485
289     1     0  0.539924  0.460076
294     1     0  0.531309  0.468691
299     1     0  0.614399  0.385601
317     1     0  0.800326  0.199674
319     0     1  0.468473  0.531527
321     0     1  0.351887  0.648113
337     0     1  0.070538  0.929462
342     1     0  0.724260  0.275740
343     1     0  0.571471  0.428529
344     0     1  0.126997  0.873003
369     0     1  0.082853  0.917147
372     1     0  0.710642  0.289358
373     1     0  0.837105  0.162895
384     0     1  0.484090  0.515910
391     0     1  0.165776  0.834224
404     0     1  0.188402  0.811598
424     1     0  0.721316  0.278684
457     0     1  0.165913  0.834087
477     1     0  0.502778  0.497222
485     1     0  0.967425  0.032575

#### 繼續細分saga下features數與elastic net 係數觀其是否能有更好的效果

In [36]:
param_grid = [
              {'clf__l1_ratio': [0.3,0.5,0.8],
               'clf__C': [1.0],
               'clf__solver': ['saga'],
               'vect__max_df':[0.8],
               'vect__max_features':[1500,5000,10000,20000],
               'vect__min_df':[2],
               'vect__ngram_range': [(1,1)],
               'vect__norm':['l1','l2',None]}           
              ]
gs_lr_tfidf = GridSearchCV(tfidf_lreg_pipeline, param_grid,     # 評估
                           scoring='accuracy',
                           cv=5,
                           verbose=2,
                           n_jobs=-1)
gs_lr_tfidf.fit(X, y)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

d:\App\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('vect',
                                        TfidfVectorizer(max_df=0.8, min_df=2)),
                                       ('clf',
                                        LogisticRegression(random_state=0))]),
             n_jobs=-1,
             param_grid=[{'clf__C': [1.0], 'clf__l1_ratio': [0.3, 0.5, 0.8],
                          'clf__solver': ['saga'], 'vect__max_df': [0.8],
                          'vect__max_features': [1500, 5000, 10000, 20000],
                          'vect__min_df': [2], 'vect__ngram_range': [(1, 1)],
                          'vect__norm': ['l1', 'l2', None]}],
             scoring='accuracy', verbose=2)

In [38]:
print('最佳超參數集: %s ' % gs_lr_tfidf.best_params_)
print('交叉驗證最佳準確度: %.3f' % gs_lr_tfidf.best_score_)

最佳超參數集: {'clf__C': 1.0, 'clf__l1_ratio': 0.3, 'clf__solver': 'saga', 'vect__max_df': 0.8, 'vect__max_features': 20000, 'vect__min_df': 2, 'vect__ngram_range': (1, 1), 'vect__norm': None}
交叉驗證最佳準確度: 0.874

#### 最佳超參數集如上'clf__l1_ratio': 0.3,'vect__max_features': 20000可獲得更好的學習效果
#### max_features=20000是上述交叉驗證給予[1500,5000,10000,20000]的最大值，若繼續加大max_features亦有可能提升準確度，但學習資源的使用亦會更昂貴，兩者需要尋求平衡

In [50]:
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X, y, test_size=0.01, random_state=42)
vectorizer_2 = TfidfVectorizer(ngram_range=(1,1), max_features=20000,
                             norm=None,
                             max_df=0.8,min_df=2)
X_train_tfidf_2 = vectorizer_2.fit_transform(X_train_2)
model_2 = LogisticRegression(C=1.0, l1_ratio=0.3,solver='saga')  # C 為正則化強度
model_2.fit(X_train_tfidf_2, y_train_2)

d:\App\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

LogisticRegression(l1_ratio=0.3, solver='saga')

In [61]:
print("數字向量詞彙集:",vectorizer_2.vocabulary_.items())
y_pred_train_2 = model_2.predict(X_train_tfidf_2)
print("訓練集準確率:",accuracy_score(y_train_2, y_pred_train_2))
X_test_tfidf_2 = vectorizer_2.transform(X_test_2)
y_pred_test_2 = model_2.predict(X_test_tfidf_2)
print("測試集準確率:",accuracy_score(y_test_2, y_pred_test_2))
print(classification_report(y_test_2, y_pred_test_2))
y_pred_proba_2=model_2.predict_proba(X_test_tfidf_2)
df_2 = pd.DataFrame({'真實標籤':y_test_2,'預測標籤':y_pred_test_2,'類別0機率':y_pred_proba_2[:,0],'類別1機率':y_pred_proba_2[:,1]})

數字向量詞彙集: dict_items([('史蒂夫', np.int64(4003)), ('布西', np.int64(6966)), ('一位', np.int64(13)), ('負的電', np.int64(16894)), ('紐約', np.int64(14442)), ('一間', np.int64(236)), ('破舊', np.int64(13726)), ('公寓', np.int64(2675)), ('母親', np.int64(11120)), ('幫忙', np.int64(7105)), ('支付', np.int64(9258)), ('房租', np.int64(8437)), ('一個', np.int64(14)), ('漂亮', np.int64(11962)), ('鄰居', np.int64(18209)), ('名叫', np.int64(4129)), ('安吉', np.int64(6067)), ('珍妮弗', np.int64(12818)), ('比爾斯', np.int64(11190)), ('結婚', np.int64(14525)), ('沒有', np.int64(11383)), ('擔任', np.int64(9203)), ('主角', np.int64(1081)), ('意外', np.int64(7989)), ('陌生人', np.int64(18747)), ('那裡', np.int64(18160)), ('提供', np.int64(9045)), ('資金', np.int64(16979)), ('已經', np.int64(6825)), ('成功', np.int64(8225)), ('冒險', np.int64(2772)), ('東西', np.int64(10516)), ('保時捷', np.int64(2028)), ('財務', np.int64(16902)), ('支持', np.int64(9259)), ('這部', np.int64(17744)), ('電影會', np.int64(19065)), ('阿道夫', np.int64(18728)), ('道德', np.int64(17942)), ('支柱', np.int64(9263)), ('演出', np.int64(11975)), ('這位', np.int64(17580)), ('觀眾', np.int64(16328)), ('看來', np.int64(13579)), ('這是', np.int64(17658)), ('一部', np.int64(230)), ('糟糕', np.int64(14374)), ('劇本', np.int64(3211)), ('情節', np.int64(7909)), ('隨意', np.int64(18827)), ('徘徊', np.int64(7595)), ('咆哮', np.int64(4236)), ('台詞', np.int64(3981)), ('雖然', np.int64(18887)), ('討人', np.int64(16392)), ('喜歡', np.int64(4450)), ('很多', np.int64(7520)), ('令人', np.int64(1560)), ('討厭', np.int64(16394)), ('材料', np.int64(10472)), ('角色', np.int64(16343)), ('二流', np.int64(1253)), ('時間', np.int64(9893)), ('畢竟', np.int64(13115)), ('起來', np.int64(17103)), ('很漂亮', np.int64(7548)), ('星際', np.int64(9816)), ('之門', np.int64(1158)), ('講述', np.int64(16709)), ('名為', np.int64(4135)), ('團隊', np.int64(4733)), ('透過', np.int64(17543)), ('裝置', np.int64(16131)), ('進行', np.int64(17847)), ('探索', np.int64(8972)), ('一邊', np.int64(229)), ('等待', np.int64(14173)), ('驚喜', np.int64(19635)), ('上映', np.int64(355)), ('我時', np.int64(8293)), ('不時', np.int64(575)), ('看過', np.int64(13608)), ('這個', np.int64(17584)), ('系列', np.int64(14376)), ('上次', np.int64(363)), ('一集', np.int64(239)), ('到底', np.int64(3051)), ('像是', np.int64(2326)), ('很棒', np.int64(7541)), ('印象', np.int64(3671)), ('事實', np.int64(1225)), ('相去', np.int64(13516)), ('甚遠', np.int64(12994)), ('簡單', np.int64(14238)), ('科幻', np.int64(13880)), ('有史', np.int64(10283)), ('有趣', np.int64(10339)), ('興奮', np.int64(15355)), ('小說', np.int64(6568)), ('什麼', np.int64(1462)), ('因為', np.int64(4651)), ('驚嘆', np.int64(19636)), ('前提', np.int64(3116)), ('價值', np.int64(2341)), ('遠遠', np.int64(18002)), ('超過', np.int64(17141)), ('所基', np.int64(8446)), ('認為', np.int64(16557)), ('例子', np.int64(1968)), ('一種', np.int64(182)), ('合適', np.int64(4055)), ('媒體', np.int64(5948)), ('能夠', np.int64(15163)), ('不受', np.int64(488)), ('觀看', np.int64(16327)), ('他們', np.int64(1489)), ('情況', np.int64(7908)), ('隨著', np.int64(18836)), ('推移', np.int64(9016)), ('而產生', np.int64(14990)), ('熟悉', np.int64(12401)), ('並且', np.int64(739)), ('增加', np.int64(5202)), ('暫停', np.int64(9992)), ('能力', np.int64(15162)), ('難以', np.int64(18933)), ('置信', np.int64(14821)), ('一切都是', np.int64(36)), ('出色', np.int64(2887)), ('寫作', np.int64(6320)), ('工作', np.int64(6771)), ('人員', np.int64(1379)), ('對節', np.int64(6459)), ('目的', np.int64(13488)), ('奉獻', np.int64(5686)), ('結果', np.int64(14532)), ('過去', np.int64(17895)), ('年裡', np.int64(7160)), ('不斷', np.int64(571)), ('偉大', np.int64(2151)), ('害怕', np.int64(6177)), ('改變', np.int64(9304)), ('挑戰', np.int64(8888)), ('幾季', np.int64(7213)), ('關注', np.int64(18610)), ('行星', np.int64(16023)), ('總是', np.int64(14756)), ('迫在眉睫', np.int64(17464)), ('劇集', np.int64(3226)), ('相當', np.int64(13535)), ('相關', np.int64(13554)), ('威脅', np.int64(5926)), ('第五', np.int64(14142)), ('第七', np.int64(14118)), ('越來', np.int64(17146)), ('專注', np.int64(6424)), ('地球', np.int64(4856)), ('攻擊', np.int64(9309)), ('本季', np.int64(10429)), ('幾乎', np.int64(7195)), ('藉口', np.int64(15862)), ('第八', np.int64(14146)), ('雜的', np.int64(18913)), ('一季', np.int64(79)), ('一連串', np.int64(226)), ('包括', np.int64(3391)), ('問題', np.int64(4410)), ('提及', np.int64(9052)), ('時刻', np.int64(9859)), ('特色', np.int64(12613)), ('第九', np.int64(14128)), ('第十', np.int64(14151)), ('旅行', np.int64(9710)), ('敵人', np.int64(9434)), ('傑克', np.int64(2236)), ('奧尼爾', np.int64(5721)), ('人類', np.int64(1457)), ('戰鬥', np.int64(8399)), ('一場', np.int64(67)), ('基本上', np.int64(5038)), ('推到', np.int64(9005)), ('這在', np.int64(17612)), ('恥辱', np.int64(7852)), ('每個', np.int64(11130)), ('星球', np.int64(9811)), ('呈現', np.int64(4200)), ('潛力', np.int64(12075)), ('神秘性', np.int64(13803)), ('衝突', np.int64(16053)), ('精彩', np.int64(14336)), ('該劇', np.int64(16531)), ('本質', np.int64(10447)), ('編劇們', np.int64(14727)), ('大膽', np.int64(5492)), ('強硬', np.int64(7436)), ('我該', np.int64(8335)), ('高質量', np.int64(19735)), ('結局', np.int64(14529)), ('休息', np.int64(1717)), ('感覺', np.int64(8097)), ('繼續', np.int64(14789)), ('參與', np.int64(3742)), ('專業', np.int64(6421)), ('人士', np.int64(1384)), ('敘述', np.int64(9375)), ('內容', np.int64(2542)), ('回到', np.int64(4626)), ('開始', np.int64(18536)), ('性質', np.int64(7826)), ('可行', np.int64(3966)), ('熱烈', np.int64(12428)), ('歡迎', np.int64(10995)), ('最終', np.int64(10202)), ('事情', np.int64(1227)), ('還是', np.int64(18104)), ('這樣', np.int64(17681)), ('很難', np.int64(7571)), ('發現', np.int64(13309)), ('結束', np.int64(14531)), ('無論', np.int64(12298)), ('時間裡', np.int64(9894)), ('一道', np.int64(228)), ('美麗', np.int64(14872)), ('風景', np.int64(19475)), ('劇組', np.int64(3220)), ('出演', np.int64(2875)), ('真實', np.int64(13623)), ('證明', np.int64(16737)), ('我們', np.int64(8257)), ('將永遠', np.int64(6394)), ('記住', np.int64(16404)), ('作為', np.int64(1890)), ('集體', np.int64(18878)), ('大學裡', np.int64(5430)), ('放映', np.int64(9329)), ('過這部', np.int64(17926)), ('幾次', np.int64(7220)), ('每次', np.int64(11142)), ('電影時', np.int64(19063)), ('處女', np.int64(15928)), ('之外', np.int64(1105)), ('人數', np.int64(1402)), ('增長', np.int64(5205)), ('過的', np.int64(17917)), ('任何人', np.int64(1626)), ('看一遍', np.int64(13566)), ('一段', np.int64(151)), ('才能', np.int64(8520)), ('進入', np.int64(17827)), ('整個', np.int64(9416)), ('房間', np.int64(8439)), ('尖叫', np.int64(6599)), ('喊叫', np.int64(4432)), ('大喊大叫', np.int64(5414)), ('沉浸', np.int64(11368)), ('觀影', np.int64(16324)), ('體驗', np.int64(19682)), ('寫得', np.int64(6324)), ('表演', np.int64(16070)), ('垃圾', np.int64(4948)), ('擁有', np.int64(9191)), ('坎坷', np.int64(4916)), ('朋友', np.int64(10354)), ('相比', np.int64(13533)), ('唯一一', np.int64(4377)), ('有過', np.int64(10342)), ('這種', np.int64(17706)), ('一開始', np.int64(235)), ('樸素', np.int64(10872)), ('喜劇', np.int64(4440)), ('中途', np.int64(1005)), ('變成', np.int64(16789)), ('情節劇', np.int64(7911)), ('約翰', np.int64(14395)), ('加菲貓', np.int64(3284)), ('成為', np.int64(8237)), ('明星', np.int64(9780)), ('理所', np.int64(12890)), ('當然', np.int64(13203)), ('弗裡', np.int64(7388)), ('林恩', np.int64(10539)), ('忽視', np.int64(7784)), ('四個', np.int64(4595)), ('女兒', np.int64(5776)), ('感情', np.int64(8089)), ('對象', np.int64(6471)), ('英俊', np.int64(15536)), ('迷人', np.int64(17471)), ('愛上', np.int64(8019)), ('大部分', np.int64(5511)), ('榮譽', np.int64(10817)), ('邁克爾', np.int64(18067)), ('華納', np.int64(15656)), ('兄弟', np.int64(2370)), ('男主角', np.int64(13084)), ('堅持', np.int64(5071)), ('野餐', np.int64(18343)), ('場景', np.int64(5096)), ('外景', np.int64(5277)), ('拍攝', np.int64(8799)), ('其成', np.int64(2737)), ('影片', np.int64(7489)), ('亮點', np.int64(1362)), ('足以', np.int64(17165)), ('范妮', np.int64(15562)), ('赫斯特', np.int64(17070)), ('肥皂', np.int64(15103)), ('傑作', np.int64(2235)), ('演員陣容', np.int64(12010)), ('公平', np.int64(2676)), ('圖形', np.int64(4705)), ('殘酷', np.int64(11095)), ('給人', np.int64(14564)), ('刺激', np.int64(3070)), ('純粹', np.int64(14447)), ('令人不安', np.int64(1561)), ('劇透', np.int64(3222)), ('怪物', np.int64(7830)), ('習慣', np.int64(14897)), ('伯特', np.int64(1747)), ('英格蘭德', np.int64(15554)), ('白痴', np.int64(13339)), ('一樣', np.int64(146)), ('禁止', np.int64(13823)), ('足球', np.int64(17169)), ('運動員', np.int64(17874)), ('睡覺', np.int64(13663)), ('試圖', np.int64(16503)), ('警察', np.int64(16749)), ('覺得', np.int64(16316)), ('演員', np.int64(11978)), ('一拖再拖', np.int64(108)), ('恐怖', np.int64(7842)), ('那樣', np.int64(18156)), ('回報', np.int64(4631)), ('還好', np.int64(18093)), ('第二', np.int64(14129)), ('會變', np.int64(10252)), ('會給', np.int64(10244)), ('靈感', np.int64(19207)), ('書籍', np.int64(10071)), ('人來', np.int64(1373)), ('你會', np.int64(1908)), ('我承認', np.int64(8289)), ('確實', np.int64(13753)), ('混合', np.int64(11806)), ('不僅僅', np.int64(460)), ('人們', np.int64(1374)), ('炫耀', np.int64(12165)), ('中心', np.int64(912)), ('包含', np.int64(3388)), ('英雄', np.int64(15560)), ('處理', np.int64(15931)), ('當我', np.int64(13186)), ('我並', np.int64(8248)), ('抱太大', np.int64(8695)), ('希望', np.int64(7010)), ('這裡', np.int64(17723)), ('有類', np.int64(10348)), ('經歷', np.int64(14627)), ('不幸', np.int64(546)), ('看得', np.int64(13589)), ('嚴肅', np.int64(4584)), ('我關', np.int64(8346)), ('不起', np.int64(661)), ('涵蓋', np.int64(11756)), ('這一點', np.int64(17561)), ('殺手', np.int64(11104)), ('電影裡', np.int64(19094)), ('幻覺', np.int64(7184)), ('它們', np.int64(6030)), ('很少', np.int64(7527)), ('相距', np.int64(13549)), ('很遠', np.int64(7565)), ('退化', np.int64(17510)), ('名人', np.int64(4125)), ('死亡', np.int64(11067)), ('競賽', np.int64(14072)), ('插曲', np.int64(9070)), ('一點', np.int64(253)), ('搞笑', np.int64(9114)), ('有人', np.int64(10267)), ('唐納', np.int64(4371)), ('弗雷', np.int64(7396)), ('論文', np.int64(16656)), ('驚訝', np.int64(19648)), ('剛才', np.int64(3137)), ('理查德', np.int64(12894)), ('斯特', np.int64(9581)), ('執導', np.int64(5003)), ('皇家', np.int64(13398)), ('閃光', np.int64(18511)), ('我還', np.int64(8342)), ('不太好', np.int64(515)), ('科姆', np.int64(13875)), ('麥克道', np.int64(19854)), ('再也', np.int64(2755)), ('機會', np.int64(10902)), ('失望', np.int64(5648)), ('時候', np.int64(9856)), ('電視', np.int64(19122)), ('再次', np.int64(2759)), ('書中', np.int64(10065)), ('尖銳', np.int64(6604)), ('轉移', np.int64(17372)), ('屏幕', np.int64(6703)), ('不當', np.int64(610)), ('想像', np.int64(7955)), ('一群', np.int64(198)), ('高中生', np.int64(19685)), ('模仿', np.int64(10856)), ('它會', np.int64(6036)), ('可怕', np.int64(3932)), ('平淡', np.int64(7134)), ('成熟', np.int64(8238)), ('眼光', np.int64(13637)), ('回顧', np.int64(4644)), ('失敗', np.int64(5643)), ('讀過', np.int64(16779)), ('這本書', np.int64(17672)), ('只能', np.int64(3911)), ('電影以', np.int64(19029)), ('魯迪', np.int64(19800)), ('斯塔', np.int64(9543)), ('伯格', np.int64(1741)), ('剛剛', np.int64(3134)), ('發明', np.int64(13298)), ('可悲', np.int64(3935)), ('背叛', np.int64(15123)), ('中關', np.int64(1018)), ('評論', np.int64(16483)), ('高興', np.int64(19725)), ('天才', np.int64(5543)), ('許是', np.int64(16453)), ('一代', np.int64(8)), ('最偉大', np.int64(10103)), ('說家', np.int64(16609)), ('那部', np.int64(18162)), ('作品', np.int64(1876)), ('欣賞', np.int64(10949)), ('摩爾', np.int64(9150)), ('詹姆斯', np.int64(16544)), ('邦德', np.int64(18168)), ('詞來', np.int64(16494)), ('描述', np.int64(9042)), ('芭芭拉', np.int64(15502)), ('斯坦', np.int64(9535)), ('威克', np.int64(5904)), ('吸引', np.int64(4177)), ('附加', np.int64(18738)), ('幸福', np.int64(7169)), ('白金', np.int64(13345)), ('金發', np.int64(18375)), ('淘金者', np.int64(11767)), ('驚人', np.int64(19632)), ('想要', np.int64(7975)), ('追求', np.int64(17497)), ('性感', np.int64(7817)), ('優秀', np.int64(2354)), ('自我', np.int64(15294)), ('原始', np.int64(3708)), ('扭曲', np.int64(8615)), ('庫爾特', np.int64(7274)), ('拉塞', np.int64(8731)), ('眼睛', np.int64(13643)), ('傳達', np.int64(2291)), ('大多', np.int64(5424)), ('數演員', np.int64(9464)), ('話語', np.int64(16529)), ('政府', np.int64(9338)), ('記得', np.int64(16405)), ('這些', np.int64(17575)), ('我花', np.int64(8325)), ('幾年', np.int64(7214)), ('網上', np.int64(14704)), ('找到', np.int64(8629)), ('不記', np.int64(650)), ('標題', np.int64(10854)), ('搜索', np.int64(9110)), ('出售', np.int64(2861)), ('錄像', np.int64(18423)), ('忍不住', np.int64(7757)), ('感到', np.int64(8080)), ('有點', np.int64(10350)), ('懷舊', np.int64(8166)), ('不用', np.int64(609)), ('無聊', np.int64(12286)), ('里德', np.int64(18275)), ('煩人', np.int64(12390)), ('弗洛拉', np.int64(7373)), ('布森', np.int64(6940)), ('總體', np.int64(14767)), ('電影並', np.int64(19027)), ('值得一看', np.int64(2130)), ('觀點', np.int64(16335)), ('當地', np.int64(13173)), ('商店', np.int64(4388)), ('美元', np.int64(14834)), ('弗羅', np.int64(7375)), ('我覺', np.int64(8331)), ('不錯', np.int64(673)), ('適合', np.int64(18007)), ('低成本', np.int64(1826)), ('這對', np.int64(17624)), ('初學者', np.int64(2992)), ('是關', np.int64(9837)), ('雪人', np.int64(18958)), ('值得', np.int64(2127)), ('封面', np.int64(6358)), ('還不錯', np.int64(18083)), ('一根', np.int64(137)), ('世界', np.int64(692)), ('故事', np.int64(9346)), ('多麼', np.int64(5366)), ('很傻', np.int64(7515)), ('靈活', np.int64(19209)), ('蠟燭', np.int64(15995)), ('尋找', np.int64(6434)), ('充滿', np.int64(2378)), ('雙關語', np.int64(18903)), ('恐怖片', np.int64(7846)), ('那麼', np.int64(18165)), ('檢查', np.int64(10928)), ('加拿大', np.int64(3267)), ('導演', np.int64(6480)), ('文森佐', np.int64(9497)), ('塔利', np.int64(5129)), ('智慧', np.int64(9972)), ('立方', np.int64(14047)), ('藝術', np.int64(15875)), ('影院', np.int64(7496)), ('掀起', np.int64(8928)), ('風暴', np.int64(19478)), ('我個', np.int64(8256)), ('年代', np.int64(7143)), ('描繪', np.int64(9038)), ('被困', np.int64(16094)), ('構想', np.int64(10822)), ('一套', np.int64(77)), ('鏡頭', np.int64(18463)), ('中將', np.int64(897)), ('想法', np.int64(7971)), ('引向', np.int64(7345)), ('方向', np.int64(9676)), ('熱切', np.int64(12413)), ('的後續', np.int64(13372)), ('行動', np.int64(16014)), ('五年', np.int64(1277)), ('項目', np.int64(19339)), ('高興地', np.int64(19726)), ('賽弗', np.int64(17030)), ('在世界上', np.int64(4746)), ('地位', np.int64(4787)), ('合乎', np.int64(4035)), ('邏輯', np.int64(18136)), ('一系列', np.int64(191)), ('事件', np.int64(1219)), ('陷入', np.int64(18783)), ('無法', np.int64(12256)), ('控制', np.int64(8997)), ('境地', np.int64(5191)), ('不想', np.int64(559)), ('透露', np.int64(17544)), ('多情', np.int64(5324)), ('樂趣', np.int64(10842)), ('道路', np.int64(17951)), ('當今', np.int64(13154)), ('時代', np.int64(9848)), ('頭腦', np.int64(19412)), ('多個', np.int64(5299)), ('耳目一新', np.int64(15004)), ('摩根', np.int64(9148)), ('沙利文', np.int64(11397)), ('傑里', np.int64(2262)), ('諾瑟姆', np.int64(16683)), ('最溫', np.int64(10190)), ('公司', np.int64(2669)), ('僱用', np.int64(2337)), ('美國', np.int64(14840)), ('地方', np.int64(4837)), ('研討會', np.int64(13713)), ('困惑', np.int64(4661)), ('剃須', np.int64(3082)), ('奶酪', np.int64(5819)), ('平凡', np.int64(7114)), ('話題', np.int64(16530)), ('福斯特', np.int64(13833)), ('無可', np.int64(12225)), ('挑剔', np.int64(8887)), ('露西', np.int64(19195)), ('少女', np.int64(6588)), ('定義', np.int64(6144)), ('不屑', np.int64(540)), ('一顧', np.int64(248)), ('這並', np.int64(17569)), ('奇怪', np.int64(5670)), ('正處', np.int64(11017)), ('婚姻', np.int64(5942)), ('告訴', np.int64(4205)), ('生活', np.int64(13024)), ('並不像', np.int64(714)), ('表面', np.int64(16077)), ('不會', np.int64(576)), ('做會', np.int64(2182)), ('削弱', np.int64(3085)), ('其餘', np.int64(2743)), ('影響', np.int64(7499)), ('曲折', np.int64(10017)), ('展示', np.int64(6708)), ('看似', np.int64(13577)), ('普通人', np.int64(9933)), ('天賦', np.int64(5555)), ('將他們', np.int64(6371)), ('帶出', np.int64(7079)), ('當他', np.int64(13155)), ('推入', np.int64(9003)), ('翻版', np.int64(14910)), ('陰謀', np.int64(18774)), ('驚悚片', np.int64(19645)), ('偏執', np.int64(2162)), ('點的', np.int64(19963)), ('偉大之處', np.int64(2152)), ('意識', np.int64(8008)), ('虛假', np.int64(15932)), ('身份', np.int64(17234)), ('謎題', np.int64(16694)), ('一部分', np.int64(231)), ('主題', np.int64(1083)), ('不知情', np.int64(618)), ('悄悄', np.int64(7871)), ('震驚', np.int64(19147)), ('區別', np.int64(3437)), ('背景', np.int64(15130)), ('微薄', np.int64(7628)), ('預算', np.int64(19360)), ('未知', np.int64(10406)), ('視野', np.int64(16295)), ('踏上', np.int64(17220)), ('穿越', np.int64(14021)), ('迷宮', np.int64(17480)), ('奇妙', np.int64(5667)), ('旅程', np.int64(9709)), ('靈巧', np.int64(19205)), ('角度', np.int64(16340)), ('數位', np.int64(9445)), ('大樓', np.int64(5454)), ('堅固', np.int64(5065)), ('辦公大樓', np.int64(17399)), ('顏色', np.int64(19436)), ('微不足道', np.int64(7617)), ('合在一起', np.int64(4040)), ('富有', np.int64(6238)), ('同情心', np.int64(4107)), ('人物', np.int64(1415)), ('質疑', np.int64(17011)), ('眼前', np.int64(13638)), ('懦夫', np.int64(8147)), ('自信', np.int64(15268)), ('男人', np.int64(13085)), ('他會', np.int64(1511)), ('大衛', np.int64(5499)), ('利特', np.int64(3038)), ('表現', np.int64(16073)), ('居住', np.int64(6675)), ('秘密', np.int64(13919)), ('看起', np.int64(13605)), ('黑衣人', np.int64(19931)), ('借來', np.int64(2114)), ('精心', np.int64(14338)), ('計算', np.int64(16389)), ('懸念', np.int64(8170)), ('練習', np.int64(14746)), ('識別', np.int64(16741)), ('雙重', np.int64(18901)), ('間諜', np.int64(18582)), ('專家', np.int64(6419)), ('心理', np.int64(7732)), ('遊戲', np.int64(17858)), ('經常', np.int64(14608)), ('充分利用', np.int64(2373)), ('密碼', np.int64(6227)), ('她終', np.int64(5826)), ('賦予', np.int64(17007)), ('手套', np.int64(8486)), ('麗塔', np.int64(19836)), ('冷漠', np.int64(2806)), ('警惕', np.int64(16752)), ('美人', np.int64(14832)), ('出現', np.int64(2880)), ('之中', np.int64(1091)), ('通過', np.int64(17788)), ('冰冷', np.int64(2786)), ('凝視', np.int64(2818)), ('力量', np.int64(3241)), ('滿意', np.int64(11950)), ('模棱', np.int64(10864)), ('兩可', np.int64(2616)), ('方式', np.int64(9677)), ('鈴聲', np.int64(18397)), ('一幕', np.int64(94)), ('中為', np.int64(951)), ('歡呼', np.int64(10986)), ('完美', np.int64(6118)), ('最後時刻', np.int64(10156)), ('陰鬱', np.int64(18780)), ('回憶', np.int64(4635)), ('壓倒性', np.int64(5223)), ('莫名其妙', np.int64(15616)), ('矩陣', np.int64(13681)), ('解藥', np.int64(16357)), ('現在', np.int64(12858)), ('精湛', np.int64(14341)), ('忠實', np.int64(7768)), ('粉絲', np.int64(14307)), ('帶著', np.int64(7084)), ('胞胎', np.int64(15140)), ('推薦給', np.int64(9021)), ('年齡', np.int64(7167)), ('孩子', np.int64(6002)), ('打鬥場', np.int64(8578)), ('暴力', np.int64(9997)), ('嚇人', np.int64(4570)), ('超出', np.int64(17127)), ('針對', np.int64(18393)), ('兒童', np.int64(2520)), ('動畫片', np.int64(3343)), ('期待', np.int64(10372)), ('削減', np.int64(3086)), ('推薦', np.int64(9020)), ('這件', np.int64(17578)), ('整部', np.int64(9430)), ('發瘋', np.int64(13312)), ('永恆', np.int64(11294)), ('基因', np.int64(5020)), ('巔峰', np.int64(6760)), ('狀態', np.int64(12649)), ('文森特', np.int64(9498)), ('明內利', np.int64(9769)), ('時尚', np.int64(9863)), ('指導', np.int64(8864)), ('音樂數', np.int64(19310)), ('從頭', np.int64(7615)), ('娛樂', np.int64(5930)), ('微笑', np.int64(7626)), ('著觀', np.int64(15750)), ('不再', np.int64(469)), ('對話', np.int64(6470)), ('高潮', np.int64(19715)), ('分鐘', np.int64(2941)), ('音樂', np.int64(19298)), ('序列', np.int64(7240)), ('電影史', np.int64(19042)), ('最美', np.int64(10204)), ('魔法', np.int64(19779)), ('顯然', np.int64(19459)), ('源自', np.int64(11875)), ('參與者', np.int64(3743)), ('內心', np.int64(2548)), ('靈魂', np.int64(19210)), ('必看', np.int64(7749)), ('其他人', np.int64(2732)), ('比拉', np.int64(11183)), ('更好', np.int64(10031)), ('地欣賞', np.int64(4844)), ('本身', np.int64(10448)), ('大雜', np.int64(5523)), ('實質', np.int64(6297)), ('混淆', np.int64(11811)), ('明確', np.int64(9787)), ('兩種', np.int64(2637)), ('女性', np.int64(5788)), ('某種', np.int64(10567)), ('將人類', np.int64(6369)), ('神秘', np.int64(13802)), ('開發', np.int64(18558)), ('度假', np.int64(7253)), ('勝地', np.int64(3352)), ('超越', np.int64(17138)), ('城市', np.int64(4999)), ('邊界', np.int64(18129)), ('解答', np.int64(16355)), ('關心', np.int64(18590)), ('進展', np.int64(17838)), ('接近', np.int64(8995)), ('產生共鳴', np.int64(13040)), ('即使如此', np.int64(3677)), ('充其量', np.int64(2372)), ('參差', np.int64(3737)), ('不齊', np.int64(687)), ('視覺', np.int64(16291)), ('深刻', np.int64(11778)), ('局面', np.int64(6673)), ('數量', np.int64(9482)), ('發展', np.int64(13290)), ('為代價', np.int64(12174)), ('圖片', np.int64(4718)), ('唯一', np.int64(4376)), ('原因', np.int64(3705)), ('吉米', np.int64(4090)), ('法倫', np.int64(11440)), ('九年', np.int64(1176)), ('迷戀', np.int64(17483)), ('六夜', np.int64(2705)), ('現場', np.int64(12862)), ('第一年', np.int64(14105)), ('洋基', np.int64(11547)), ('鐵桿', np.int64(18484)), ('球迷', np.int64(12883)), ('最後分鐘', np.int64(10138)), ('痛苦', np.int64(13257)), ('當他們', np.int64(13156)), ('播放', np.int64(9183)), ('比賽', np.int64(11208)), ('片段', np.int64(12

In [ ]:
df_2[(df_2['預測標籤']!=df_2['真實標籤'])]

     真實標籤  預測標籤     類別0機率     類別1機率
1       0     1  0.150536  0.849464
4       0     1  0.340014  0.659986
20      1     0  0.937388  0.062612
24      0     1  0.261318  0.738682
28      1     0  0.537476  0.462524
37      1     0  0.590007  0.409993
38      0     1  0.137048  0.862952
40      1     0  0.668598  0.331402
47      0     1  0.451932  0.548068
48      1     0  0.630255  0.369745
49      1     0  0.832093  0.167907
51      0     1  0.388372  0.611628
58      0     1  0.462674  0.537326
60      0     1  0.362585  0.637415
82      0     1  0.283231  0.716769
85      1     0  0.554023  0.445977
90      0     1  0.119109  0.880891
91      1     0  0.576835  0.423165
92      1     0  0.975049  0.024951
114     1     0  0.629533  0.370467
160     0     1  0.449000  0.551000
166     0     1  0.450107  0.549893
167     0     1  0.478289  0.521711
173     0     1  0.484749  0.515251
176     0     1  0.178022  0.821978
179     1     0  0.898066  0.101934
181     0     1  0.499935  0.500065
194     1     0  0.579702  0.420298
204     0     1  0.393706  0.606294
221     1     0  0.727067  0.272933
225     0     1  0.310316  0.689684
234     0     1  0.365696  0.634304
239     1     0  0.743462  0.256538
242     1     0  0.505900  0.494100
252     0     1  0.197948  0.802052
268     0     1  0.413987  0.586013
271     0     1  0.499935  0.500065
272     1     0  0.520255  0.479745
294     1     0  0.638419  0.361581
299     1     0  0.574211  0.425789
317     1     0  0.955044  0.044956
319     0     1  0.470514  0.529486
321     0     1  0.335858  0.664142
337     0     1  0.075346  0.924654
344     0     1  0.084521  0.915479
369     0     1  0.075706  0.924294
372     1     0  0.739943  0.260057
373     1     0  0.976651  0.023349
391     0     1  0.085859  0.914141
399     0     1  0.463103  0.536897
417     0     1  0.348357  0.651643
424     1     0  0.875877  0.124123
429     1     0  0.597065  0.402935
457     0     1  0.218618  0.781382
477     1     0  0.726759  0.273241
485     1     0  0.764427  0.235573

In [68]:
param_grid = [
              {'clf__l1_ratio': [0.3,0.5,0.8],
               'clf__C': [1.0],
               'clf__solver': ['saga'],
               'vect__max_df':[0.8],
               'vect__max_features':[20000,30000],
               'vect__min_df':[2],
               'vect__ngram_range': [(1,1)],
               'vect__norm':['l1','l2',None]},
               {'clf__l1_ratio': [0],
               'clf__C': [1.0],
               'clf__solver': ['sag'],
               'vect__max_df':[0.8],
               'vect__max_features':[10000,20000,30000],
               'vect__min_df':[2],
               'vect__ngram_range': [(1,1)],
               'vect__norm':['l1','l2',None]}         
              ]
gs_lr_tfidf = GridSearchCV(tfidf_lreg_pipeline, param_grid,     # 評估
                           scoring='accuracy',
                           cv=5,
                           verbose=2,
                           n_jobs=-1)
gs_lr_tfidf.fit(X, y)

Fitting 5 folds for each of 27 candidates, totalling 135 fits

d:\App\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('vect',
                                        TfidfVectorizer(max_df=0.8, min_df=2)),
                                       ('clf',
                                        LogisticRegression(random_state=0))]),
             n_jobs=-1,
             param_grid=[{'clf__C': [1.0], 'clf__l1_ratio': [0.3, 0.5, 0.8],
                          'clf__solver': ['saga'], 'vect__max_df': [0.8],
                          'vect__max_features': [20000, 30000],
                          'vect__min_df': [2], 'vect__ngram_range': [(1, 1)],
                          'vect__norm': ['l1', 'l2', None]},
                         {'clf__C': [1.0], 'clf__l1_ratio': [0],
                          'clf__solver': ['sag'], 'vect__max_df': [0.8],
                          'vect__max_features': [10000, 20000, 30000],
                          'vect__min_df': [2], 'vect__ngram_range': [(1, 1)],
                          'vect__norm': ['l1', 'l2', None]}],
             scoring='accuracy', verbose=2)

加大max_features至30000提升準確度並不顯著，但學習資源的使用更昂貴，兩者需要尋求平衡

In [70]:
print('最佳超參數集: %s ' % gs_lr_tfidf.best_params_)
print('交叉驗證最佳準確度: %.3f' % gs_lr_tfidf.best_score_)

最佳超參數集: {'clf__C': 1.0, 'clf__l1_ratio': 0.3, 'clf__solver': 'saga', 'vect__max_df': 0.8, 'vect__max_features': 30000, 'vect__min_df': 2, 'vect__ngram_range': (1, 1), 'vect__norm': None}
交叉驗證最佳準確度: 0.875

In [71]:
X_train_3, X_test_3, y_train_3, y_test_3 = train_test_split(X, y, test_size=0.01, random_state=42)
vectorizer_3 = TfidfVectorizer(ngram_range=(1,1), max_features=30000,
                             norm=None,
                             max_df=0.8,min_df=2)
X_train_tfidf_3 = vectorizer_3.fit_transform(X_train_3)
model_3 = LogisticRegression(C=1.0, l1_ratio=0.3,solver='saga')  # C 為正則化強度
model_3.fit(X_train_tfidf_3, y_train_3)

d:\App\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

LogisticRegression(l1_ratio=0.3, solver='saga')

In [72]:
y_pred_train_3 = model_3.predict(X_train_tfidf_3)
print("訓練集準確率:",accuracy_score(y_train_3, y_pred_train_3))
X_test_tfidf_3 = vectorizer_3.transform(X_test_3)
y_pred_test_3 = model_3.predict(X_test_tfidf_3)
print("測試集準確率:",accuracy_score(y_test_3, y_pred_test_3))

訓練集準確率: 0.9325359049708207
測試集準確率: 0.8834355828220859